### PR TITLE
Make myself reviewer

### PR DESCRIPTION
**Pull request by alvaroaleman**

### CODE REVIEW

**Comment by nikhita** [comment]
Going to leave this open to check merge automation tomorrow. :)

**Comment by nikhita** [comment]
Added myself to the "approvers" section, which caused conflicts. Trying it in another PR: https://github.com/prowtest/prow-test-2/pull/4, but it looks like automatic merging requires some more magic sauce. :(

**Comment by nikhita** [comment]
(haven't enabled tide yet, just checking the approve plugin)

**Comment by nikhita** [comment]
Yay! :tada:

**Comment by alvaroaleman** [comment]
it works :)))))

**Pull request merged**
